// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOdZzaY2C0Z2NXB-jQSflpxGryzjaAhWs',
    appId: '1:927599597404:web:2af0ad60de282a8e0a5399',
    messagingSenderId: '927599597404',
    projectId: 'tickets-20e16',
    authDomain: 'tickets-20e16.firebaseapp.com',
    storageBucket: 'tickets-20e16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuK1D8nCweNcW0OiOv5_JBT27ZT22GztA',
    appId: '1:927599597404:android:ec4e6ba76a8f46dc0a5399',
    messagingSenderId: '927599597404',
    projectId: 'tickets-20e16',
    storageBucket: 'tickets-20e16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6PjteYgpFhdDzdGSrHni_0nxiD3NHiOg',
    appId: '1:927599597404:ios:d5e5ddd5832378a70a5399',
    messagingSenderId: '927599597404',
    projectId: 'tickets-20e16',
    storageBucket: 'tickets-20e16.firebasestorage.app',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6PjteYgpFhdDzdGSrHni_0nxiD3NHiOg',
    appId: '1:927599597404:ios:d5e5ddd5832378a70a5399',
    messagingSenderId: '927599597404',
    projectId: 'tickets-20e16',
    storageBucket: 'tickets-20e16.firebasestorage.app',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOdZzaY2C0Z2NXB-jQSflpxGryzjaAhWs',
    appId: '1:927599597404:web:4b90d6675b4596690a5399',
    messagingSenderId: '927599597404',
    projectId: 'tickets-20e16',
    authDomain: 'tickets-20e16.firebaseapp.com',
    storageBucket: 'tickets-20e16.firebasestorage.app',
  );
}
